import json
from ollama import chat

## System prompt for the Planner Agent
## Describe its role, the expected output format, and the rules it must follow when generating a navigation plan.
## These are fairly similar to the Analyst Agent, but with a focus on creating a plan based on the requirements provided by the Analyst Agent.
SYSTEM_PROMPT = """
You are a planning engineer for a robot navigation system.
Your job is to take validated software requirements and produce a navigation plan.

You must output ONLY a single valid JSON object.
Do not include any explanation, markdown formatting, or extra text.

The JSON must have exactly these keys:
{
  "strategy": "string",
  "decisions": ["string", "string", "string"],
  "stop_condition": "string"
}

Rules:
- "strategy" describes the overall navigation strategy as a string.
- "decisions" is a list of decision rules the robot can follow during navigation.
  Each item must be a string.
- "stop_condition" describes the exact situation in which the robot must stop.
"""


## Function to validate the plan generated by the Planner Agent
## It should first check that the parameter it receives is of the correct type. 
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_plan(data):
    if not isinstance(data, dict):
        raise ValueError("Planner output is not a dictionary.")

    required_keys = {"strategy", "decisions", "stop_condition"}

    missing = required_keys - data.keys()
    if missing:
        raise ValueError(f"Missing required keys: {missing}")

    extra = data.keys() - required_keys
    if extra:
        raise ValueError(f"Unexpected extra keys: {extra}")

    if not isinstance(data["strategy"], str):
        raise ValueError("'strategy' must be a string.")

    if not isinstance(data["decisions"], list):
        raise ValueError("'decisions' must be a list.")

    if not all(isinstance(d, str) for d in data["decisions"]):
        raise ValueError("Every item in 'decisions' must be a string.")

    if not isinstance(data["stop_condition"], str):
        raise ValueError("'stop_condition' must be a string.")

    print("=== Validation passed ===")
    print(data)
    print("=========================\n")


## Function to run the Planner Agent
## It takes the requirements generated by the Analyst Agent as input, sends them to the Planner Agent. Just like you did with the Analyst Agent.
## Take the response from the Planner Agent (Qwen), parse it and validate it using the validate_plan function, and return the validated plan.
def run_planner(requirement):
    response = chat(
        model="qwen3:8b",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(requirement)},
        ],
    )

    raw = response.message.content
    print("=== Raw Qwen output ===")
    print(raw)
    print("=== End of raw output ===\n")

    # Clean possible markdown code fences like ```json ... ```
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("```")[1]
        if cleaned.startswith("json"):
            cleaned = cleaned[4:]
    cleaned = cleaned.strip()

    data = json.loads(cleaned)
    validate_plan(data)
    return data